name: Automated build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created, edited]

  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore ChummerGenSR4.sln

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: run minver
        id: version
        uses: Stelzi79/action-minver@3.0.1
        with:
          auto-increment: patch
          build-metadata: ${{ steps.short-sha.outputs.sha }}
          default-pre-release-phase: beta
          minimum-major-minor: 0.1
          tag-prefix: v

      - name: Set project versions
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: |
            "**/AssemblyInfo.cs"
          version: ${{ steps.version.outputs.version }}

      - name: Build the solution
        run: msbuild ChummerGenSR4.sln /p:Configuration=Release
        
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: "ChummerGenSR4-${{ steps.version.outputs.version }}.zip"
          path: "bin/*"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: "ChummerGenSR4-${{ steps.version.outputs.version }}"
          path: "ChummerGenSR4-${{ steps.version.outputs.version }}.zip"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: run minver
        id: version
        uses: Stelzi79/action-minver@3.0.1
        with:
          auto-increment: patch
          build-metadata: ${{ steps.short-sha.outputs.sha }}
          default-pre-release-phase: beta
          minimum-major-minor: 0.1
          tag-prefix: v

      - name: Download release version
        uses: actions/download-artifact@v2.0.10
        with:
          name: "ChummerGenSR4-${{ steps.version.outputs.version }}"

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          args: ./ChummerGenSR4-${{steps.version.outputs.version}}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
